#!/bin/sh
# lauf_launchicon - create a desktop launcher for Lauf.

read -e -p "Where is lauf's directory?: " LAUF_DIR
if [ ! -d "${LAUF_DIR}" ];then
    echo "That directory doesen't exist!"
    exit 1
fi

LAUF_FILE="${LAUF_DIR}/lauf"
LAUF_ICON="${LAUF_DIR}/icons/lauf.png"

read -e -p "Where do you want to save the launcher file?: " LAUF_DESKTOP

echo "#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=Lauf
Exec=${LAUF_FILE}
Icon=${LAUF_ICON}
Comment=Lauf launcher" > "$LAUF_DESKTOP"

echo "Wrote launcher info to ${LAUF_DESKTOP}"
